### ISSUE TITLE
Volume can be negative or more than 100%

### ISSUE THREAD

**Issue by cMerd** [fnzrli2011/VolumeCOntroller-Application-for-Linux-#2]
Volume can be set negative value or more than 100%: 
![20240827-101030](https://github.com/user-attachments/assets/6110ce7d-ab6c-463c-b452-b7db0ac6a82a)
![20240827-101042](https://github.com/user-attachments/assets/c683b849-1f49-4e0b-b84b-774d34b917e6)

**Comment by Mrcat2011** [comment]
I solve this problem please try Volume_COntroller.v2
